config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'users#index'
  resources :users, :organizations do
    resources :links
  end
end

app/models/link.rb
class Link < ActiveRecord::Base
  has_many :ownerships
  before_save :set_title

  private
  def set_title
    doc = Nokogiri::HTML(open( self.url ))
    self.title = doc.css('title').inner_html
  end
end

app/models/membership.rb
class Membership < ActiveRecord::Base
  belongs_to :user
  belongs_to :organization
end

app/models/organization.rb
class Organization < ActiveRecord::Base
  has_many :memberships
  has_many :users, through: :memberships
  has_many :ownerships
  has_many :links, through: :ownerships
  belongs_to :user
end

app/models/ownership.rb
class Ownership < ActiveRecord::Base
  belongs_to :link
  belongs_to :user
  belongs_to :organization
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :memberships
  has_many :organizations, through: :memberships
  has_many :ownerships
  has_many :links, through: :ownerships
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index]

  # GET /links
  # GET /links.json
  def index
    if params[:user_id]
      @links = User.find( params[:user_id] ).links
      @is_admin = User.find( params[:user_id] ) == current_user
      @name = User.find( params[:user_id] ).email
    elsif params[:organization_id]
      @org = Organization.find( params[:organization_id] )
      @name = Organization.find( params[:organization_id] ).name
      @links = @org.links
      @links = Link.all
      mem = Membership.find_by( organization: @org, user: current_user )
      @is_admin = mem && mem.is_admin
    end
  end

  # GET /links/new
  def new
    @link = Link.new
    @user = current_user
  end

  # GET /links/1/edit
  def edit
    @user = current_user
    @link = Link.find( params[:id] )
  end

  # POST /links
  # POST /links.json
  def create
    @link = current_user.links.create(link_params)

    respond_to do |format|
      if @link.save
        format.html { redirect_to user_links_path( current_user ), notice: 'Link was successfully created.' }
        format.json { render :show, status: :created, location: @link }
      else
        format.html { render :new }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /links/1
  # PATCH/PUT /links/1.json
  def update
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to user_links_path( current_user ), notice: 'Link was successfully updated.' }
        format.json { render :show, status: :ok, location: @link }
      else
        format.html { render :edit }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1
  # DELETE /links/1.json
  def destroy
    @link.destroy
    respond_to do |format|
      format.html { redirect_to user_links_path( current_user ), notice: 'Link was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link
      @link = Link.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def link_params
      params.require(:link).permit(:url)
    end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  def new
    @organization = Organization.new
  end

  def show
    @org = Organization.find( params[:id] )
    @links = @org.links
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!

  def index
    @organizations = current_user.organizations
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tabular</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <h1><%= link_to 'Tabular', root_path %></h1>
  <% if user_signed_in? %>
    <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        
  <% else %>
    <%= link_to('Login', new_user_session_path)  %>  
  <% end %>

<%= yield %>

</body>
</html>

app/views/links/_form.html.erb
<%= form_for([@user, @link]) do |f| %>
  <% if @link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% @link.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/links/edit.html.erb
<h1>Editing link</h1>

<%= render 'form' %>

<%= link_to 'Back', user_links_path %>

app/views/links/index.html.erb
<h1>Listing <%= @name %>'s links </h1>

    <% @links.each do |link| %>
        <%= link_to link.title, link.url %>

	<% if @is_admin  %>
	  <%= link_to '*', edit_user_link_path( current_user, link) %>
	  <%= link_to '&times;'.html_safe, user_link_path( current_user, link ), method: :delete %>
	<% end %>
	<br>
	<hr>
    <% end %>

<br>

<% if current_user %>
  <%= link_to 'New Link', new_user_link_path( current_user ) %>
<% end %>

app/views/links/new.html.erb
<h1>New link</h1>

<%= render 'form' %>

<%= link_to 'Back', user_links_path %>

app/views/links/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Url:</strong>
  <%= @link.url %>
</p>

<p>
  <strong>Title:</strong>
  <%= @link.title %>
</p>

<%= link_to 'Edit', edit_link_path(@link) %> |
<%= link_to 'Back', links_path %>

app/views/organizations/_form.html.erb
<%= form_for @organization do |f| %>
  <%= f.label :name %> 
  <%= f.text_field :name %> 
<% end %>

app/views/organizations/new.html.erb
<h2>Create new organization</h2>

<%= render 'form' %>

app/views/users/index.html.erb
<%= link_to 'create new organization', new_organization_path %>

<ul>
  <li><%= link_to 'me', user_links_path( current_user ) %></li>
  <% @organizations.each do |org| %>
    <li><%= link_to org.name, organization_links_path( org ) %></li>
  <% end %>
</ul>